//light(x,y,size,color)
draw_set_blend_mode(bm_subtract)
//draw_ellipse_colour(argument0-random_range(argument2-1.5,argument2+1.5),argument1-random_range((argument2/1.5)-1.5,(argument2/2)+1.5),argument0+random_range(argument2-1.5,argument2+1.5),argument1+random_range((argument2/1.5)-1.5,(argument2/2)+1.5),argument3,c_black,0)
draw_circle_colour(argument0,argument1,random_range(argument2-1.5,argument2+1.5),argument3,c_black,0)
draw_set_blend_mode(bm_normal)
